GET http://localhost:3000/

###
GET http://localhost:3000/api/product

###

GET http://localhost:3000/api/product/607e8f1b7b7868220cd87d7e

###

POST http://localhost:3000/api/product
Content-Type: application/json

{
    "name": "Dugges Amarillo",
    "price": 25,
    "description": "Humlearomatisk smak med tydlig beska, med inslag av ananas, tallbarr, honung, passionsfrukt och apelsinskal.",
    "image": "https://dugges.se/wp-content/uploads/2021/02/bottle_web3_Amarillo-1000x1978.jpg"
}

###


PATCH http://localhost:3000/api/product/607e8f1b7b7868220cd87d7e
Content-Type: application/json

{
    "name": "Dugges Test", 
    "price": 25,
    "description": "Humlearomatisk smak med tydlig beska, med inslag av ananas, tallbarr, honung, passionsfrukt och apelsinskal.", 
    "image": "https://dugges.se/wp-content/uploads/2021/02/bottle_web3_Amarillo-1000x1978.jpg"
}


### 

DELETE http://localhost:3000/api/product/607e8eec7b7868220cd87d7d


// User commands 

### 
POST http://localhost:3000/api/user/register
Content-Type: application/json

{
    "userName": "Oliver", 
    "passWord": "6krHRZ8P",
    "role": "user"
}



###
POST http://localhost:3000/api/user/login
Content-Type: application/json

{
    "userName": "Browbeans", 
    "passWord": "6krHRZ8P"
}    


### 

GET http://localhost:3000/api/user/allUsers

###

DELETE http://localhost:3000/api/user/logout

###

// Post commands 

###

GET http://localhost:3000/api/posts/allPosts

###

POST http://localhost:3000/api/posts/addPost
Content-Type: application/json

{
    "title": "Second post", 
    "body": "this is a test and lets see what happens"
}

###

PATCH  http://localhost:3000/api/posts/editPost/607ecce1f720a333c8fbd653
Content-Type: application/json

{
    "title": "Changed title on post", 
    "body": "changed body on post"
}

### 

DELETE http://localhost:3000/api/posts/deletePost/607ecce1f720a333c8fbd653