GET http://localhost:3000/

###
GET http://localhost:3000/api/product

###

GET http://localhost:3000/api/product/2

###

POST http://localhost:3000/api/product
Content-Type: application/json

{
    "name": "Dugges Tropic Thunder", 
    "price": 43,
    "description": "Mycket fruktig och syrlig smak med inslag av mango, passionsfrukt, persika och apelsin."
}

###


PUT http://localhost:3000/api/product/2
Content-Type: application/json

{
    "name": "Dugges Amarillo", 
    "price": 25,
    "description": "Humlearomatisk smak med tydlig beska, med inslag av ananas, tallbarr, honung, passionsfrukt och apelsinskal."
}


### 

DELETE http://localhost:3000/api/product/5